apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-config
  namespace: jenkins
data:
  config.json: |
    {
      "credHelpers": {
        "045552220539.dkr.ecr.eu-central-1.amazonaws.com": "ecr-login"
      }
    }
