controller:
  admin:
    username: "admin"
    password: "H@dyRlwgkI*D%DRR"
  
  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - amazon-ecr:latest

  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "2000m"
      memory: "2048Mi"

  serviceType: LoadBalancer

agent:
  enabled: true
  defaultsProviderTemplate: "jenkins-agent"
  templates:
    - name: "jenkins-agent"
      containers:
        - name: "kaniko"
          image: "gcr.io/kaniko-project/executor:latest"
          command: "/bin/sh"
          args: "-c \"cat\""
          ttyEnabled: true
          privileged: true
          resourceRequestCpu: "500m"
          resourceRequestMemory: "512Mi"
          resourceLimitCpu: "1000m"
          resourceLimitMemory: "1024Mi"

persistence:
  enabled: true
  size: "10Gi"

rbac:
  create: true
  readSecrets: true