controller:
  auth:
    jenkins:
      password: "H@dyRlwgkI*D%DRR"
  admin:
    username: "admin"
    password: "H@dyRlwgkI*D%DRR"
    existingSecret: ""
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password
  
  # Дозволити доступ з будь-якого IP
  javaOpts: "-Dhudson.model.DirectoryBrowserSupport.CSP=\"\" -Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
  jenkinsOpts: "--httpPort=8080 --httpsPort=-1"
  
  installPlugins:
    - kubernetes:4.20.0
    - workflow-aggregator:596.v8c21c963d92d
    - workflow-job:1436.vfa_244484591f
    - pipeline-stage-view:2.34
    - git:5.4.1
    - configuration-as-code:1870.vf3dc5da_115a_f
    - amazon-ecr:1.7
    - github:1.40.0
    - github-pullrequest:0.9.0
    - generic-webhook-trigger:2.2.2
    - blueocean:1.27.14
    - scm-api:696.v778d637b_a_762
    - git-client:6.0.0
    - credentials:1371.vfee6b_095f0a_3
    - credentials-binding:677.vdc9d38cb_254d

  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "2000m"
      memory: "2048Mi"

  serviceType: LoadBalancer

agent:
  enabled: true
  defaultsProviderTemplate: "jenkins-agent"
  templates:
    - name: "jenkins-agent"
      containers:
        - name: "kaniko"
          image: "gcr.io/kaniko-project/executor:latest"
          command: "/bin/sh"
          args: "-c \"cat\""
          ttyEnabled: true
          privileged: true
          resourceRequestCpu: "500m"
          resourceRequestMemory: "512Mi"
          resourceLimitCpu: "1000m"
          resourceLimitMemory: "1024Mi"

persistence:
  enabled: true
  size: "10Gi"

rbac:
  create: true
  readSecrets: true