controller:
  adminUser: "admin"
  adminPassword: "admin123"  # В продакшені використовуйте безпечніший пароль

  installPlugins:
    - kubernetes:3900.v5a_03996b_c59
    - workflow-aggregator:590.v6a_d052e5a_a_b_5
    - git:5.1.0
    - configuration-as-code:1647.ve39ca_b_829b_42
    - amazon-ecr:1.9

  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "2000m"
      memory: "2048Mi"

  serviceType: LoadBalancer

agent:
  enabled: true
  defaultsProviderTemplate: "jenkins-agent"
  templates:
    - name: "jenkins-agent"
      containers:
        - name: "kaniko"
          image: "gcr.io/kaniko-project/executor:latest"
          command: "sleep"
          args: "99d"
          ttyEnabled: true
          privileged: true
          resourceRequestCpu: "500m"
          resourceRequestMemory: "512Mi"
          resourceLimitCpu: "1000m"
          resourceLimitMemory: "1024Mi"

persistence:
  enabled: true
  storageClass: "${storage_class}"  # використовуємо змінну
  size: "10Gi"

rbac:
  create: true
  readSecrets: true